# Generated by Django 3.2.7 on 2021-10-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesas', '0002_alter_mesas_numerom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesas',
            name='numerom',
            field=models.IntegerField(),
        ),
    ]
